### ISSUE TITLE
GUI doesn't load on linux

### ISSUE THREAD

**Issue by ghost** [chrisnorman7/gmp3#4]
The program doesn't crash, it continues to run just without GUI.
This happens because there is no case for Linux in `~/.local/lib/python3.6/site-packages/sound_lib/output.py`. I added it myself, but I don't know how to send the patch upstream since this repo is not on github

This is not really a gmp3's issue

Here is the log
```
INFO:gmusicapi.Mobileclient1:!-- begin debug log --!
INFO:gmusicapi.Mobileclient1:version: 10.1.2
INFO:gmusicapi.Mobileclient1:logging to: /home/budkin/.cache/gmusicapi/log/gmusicapi.log
INFO:gmusicapi.Mobileclient1:initialized
INFO:gmusicapi.Mobileclient1:logged out
INFO:root:Starting GMP3, version 4.3.0.
ERROR:root:a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/home/budkin/Documents/gmp3/main.py", line 28, in <module>
    import db
  File "/home/budkin/Documents/gmp3/db.py", line 5, in <module>
    import config
  File "/home/budkin/Documents/gmp3/config.py", line 46, in <module>
    class Config(Section):
  File "/home/budkin/Documents/gmp3/config.py", line 126, in Config
    class system(Section):
  File "/home/budkin/Documents/gmp3/config.py", line 138, in system
    output_device_name = Option(application.output.get_device_names()[application.output.device - 1])
  File "/home/budkin/.local/lib/python3.6/site-packages/sound_lib/output.py", line 114, in get_device_names
    retrieved = retrieved.replace('(', '').replace(')', '').strip()
TypeError: a bytes-like object is required, not 'str'
```

**Comment by chrisnorman7** [comment]
I urge you to direct this to Q who owns sound_lib. He can be found [on Twitter](https://twitter.com/mongoose_q).

Good luck!
